kind: pipeline
name: HANA-CI-Build-Project

platform:
  os: linux
  arch: amd64

clone:
depth: 1

steps:
- name: HANA-CI-Builder
  image: nicklas373/oven:latest
  environment:
   tg_channel_id:
     from_secret: tg_channel_id
   tg_group_id:
     from_secret: tg_group_id
   tg_bot_id:
     from_secret: tg_bot_id
   token:
     from_secret: git_token
   tg_aln_id:
     from_secret: tg_aln_id
   telegram_fusion_id:
     from_secret: telegram_fusion_id
  commands:
  - wget https://raw.githubusercontent.com/Nicklas373/CI/CI/ci
  - chmod a+x ci
  - bash ci
