kind: pipeline
name: HANA-CI-Bot

steps:
- name: HANA-CI-Builder
  image: ubuntu:rolling
  commands:
  - apt-get update -y &&  apt-get upgrade -y
  - apt-get install -y bash wget
  - wget https://raw.githubusercontent.com/drone-mirror/Drone-CI/drone/drone-unified.sh
  - chmod a+x drone-unified.sh
  - bash drone-unified.sh
