kind: pipeline
name: HANA-CI-Build-Project

platform:
  os: linux
  arch: amd64

clone:
depth: 1

steps:
- name: HANA-CI-Builder
  image: najahi/oven:latest
  environment:
   tg_channel_id:
     from_secret: tg_channel_id
   tg_group_id:
     from_secret: tg_group_id
   tg_bot_id:
     from_secret: tg_bot_id
   token:
     from_secret: git_token
  commands:
  - run: sh -c  "$(curl -fsSL  https://github.com/nicklas373/build_kernel/raw/test/.circleci/build.sh)"
  - chmod a+x circle-unified.sh
  - bash circle-unified.sh
